package cli

import (
	"context"
	"fmt"
	"io"
	"os"
	"path/filepath"
	"sort"
	"strings"

	"github.com/grafana/hatch/pkg/block"
	"github.com/grafana/hatch/pkg/target"
)

// cmdGen is the implementation of `hatch gen`. It always operates on the
// current working directory. Target selection is via the `-targets names`
// flag; an empty value means every registered target.
func cmdGen(ctx context.Context, version string, available *target.Set, args []string, stdout, stderr io.Writer) error {
	cf := commonFlags("gen", stderr)
	if err := cf.fs.Parse(args); err != nil {
		return err
	}
	if err := ensureNoPositional(cf.fs, "gen"); err != nil {
		return err
	}
	if err := ctx.Err(); err != nil {
		return err
	}
	targets, err := selectTargets(available, *cf.targetsList)
	if err != nil {
		return err
	}
	src, err := loadSource(!*cf.noHatchSkill, version)
	if err != nil {
		return err
	}

	// Collect every target's artifacts before writing so collisions on the
	// same path (e.g., AGENTS.md is shared by Codex and OpenCode) can be
	// detected and merged rather than letting the last write silently win.
	byPath := map[string][]pending{}
	for _, t := range targets.All() {
		if err := ctx.Err(); err != nil {
			return err
		}
		arts, err := t.Generate(src)
		if err != nil {
			return fmt.Errorf("%s: %w", t.Name(), err)
		}
		for _, a := range arts {
			byPath[a.Path] = append(byPath[a.Path], pending{artifact: a, source: t.Name()})
		}
	}

	// Write in sorted path order so output is deterministic.
	paths := make([]string, 0, len(byPath))
	for p := range byPath {
		paths = append(paths, p)
	}
	sort.Strings(paths)

	for _, p := range paths {
		if err := ctx.Err(); err != nil {
			return err
		}
		group := byPath[p]
		merged, err := mergeArtifacts(p, group)
		if err != nil {
			return err
		}
		if err := writeArtifact(merged); err != nil {
			return fmt.Errorf("%s: %w", p, err)
		}
		fmt.Fprintln(stdout, formatWroteLine(merged))
	}
	return nil
}

// formatWroteLine builds the one-line `wrote ...` status message that
// hatch gen prints for each artifact. Block-mode writes use the
// editor-jumpable `path:begin-end` notation so the user can click
// straight into the hatch block; file-mode writes print just the path.
func formatWroteLine(a target.Artifact) string {
	if a.Mode != target.ModeBlock {
		return fmt.Sprintf("wrote %s", a.Path)
	}
	begin, end, ok := findBlockLineRange(a.Path, block.CurrentMarker)
	if !ok {
		return fmt.Sprintf("wrote %s", a.Path)
	}
	return fmt.Sprintf("wrote %s:%d-%d", a.Path, begin, end)
}

// findBlockLineRange returns the 1-indexed line numbers of the begin
// and end marker lines for `marker` inside the file at path. Returns
// ok=false if the file can't be read or the markers aren't found — in
// that case callers fall back to a shorter output format.
func findBlockLineRange(path, marker string) (begin, end int, ok bool) {
	data, err := os.ReadFile(path)
	if err != nil {
		return 0, 0, false
	}
	beginMarker, endMarker := block.Markers(marker)
	lines := strings.Split(string(data), "\n")
	for i, line := range lines {
		trimmed := strings.TrimSpace(line)
		if begin == 0 && trimmed == beginMarker {
			begin = i + 1
			continue
		}
		if begin != 0 && trimmed == endMarker {
			end = i + 1
			return begin, end, true
		}
	}
	return 0, 0, false
}

// pending pairs an artifact with the name of the target that produced
// it, so collision error messages can identify the responsible targets.
type pending struct {
	artifact target.Artifact
	source   string
}

// mergeArtifacts combines multiple artifacts at the same path into a single
// artifact. Callers that generate files at a shared path (e.g., Codex and
// OpenCode both writing AGENTS.md) end up here. The merge rules:
//
//   - Single artifact: return it unchanged.
//   - Multiple ModeFile artifacts: collision only allowed when every
//     artifact has byte-identical content; otherwise error (file-owned
//     paths should not be generated by more than one target).
//   - Multiple ModeBlock artifacts: take the union of unique block bodies,
//     separated by a blank line. This preserves content that any one target
//     wants included in the shared file.
//   - Mixed modes at the same path: error (indicates a target bug).
func mergeArtifacts(path string, group []pending) (target.Artifact, error) {
	if len(group) == 1 {
		return group[0].artifact, nil
	}
	first := group[0].artifact
	for _, p := range group[1:] {
		if p.artifact.Mode != first.Mode {
			return target.Artifact{}, fmt.Errorf("%s: mixed write modes from targets %s and %s", path, group[0].source, p.source)
		}
	}
	switch first.Mode {
	case target.ModeFile:
		for _, p := range group[1:] {
			if p.artifact.Content != first.Content {
				return target.Artifact{}, fmt.Errorf("%s: targets %s and %s both generate this file with different content", path, group[0].source, p.source)
			}
		}
		return first, nil
	case target.ModeBlock:
		// Collect unique non-empty bodies.
		seen := map[string]bool{}
		var bodies []string
		for _, p := range group {
			body := strings.TrimRight(p.artifact.Content, "\n")
			if body == "" || seen[body] {
				continue
			}
			seen[body] = true
			bodies = append(bodies, body)
		}
		// Drop any body that's a substring of another — common case: one
		// target generates a superset (e.g., Codex adds inlined commands
		// and agents on top of the same rules OpenCode already has) and
		// we want to keep only the superset, not duplicate the shared
		// prefix.
		var kept []string
		for i, a := range bodies {
			covered := false
			for j, b := range bodies {
				if i == j {
					continue
				}
				if len(b) > len(a) && strings.Contains(b, a) {
					covered = true
					break
				}
			}
			if !covered {
				kept = append(kept, a)
			}
		}
		return target.Artifact{
			Path:    path,
			Mode:    target.ModeBlock,
			Content: strings.Join(kept, "\n\n"),
		}, nil
	default:
		return target.Artifact{}, fmt.Errorf("%s: unknown write mode %q", path, first.Mode)
	}
}

// writeArtifact writes a single artifact relative to the current working
// directory. Block-mode artifacts are merged into the target file between
// hatch markers; file-mode artifacts overwrite the whole file.
func writeArtifact(a target.Artifact) error {
	switch a.Mode {
	case target.ModeFile:
		if err := os.MkdirAll(filepath.Dir(a.Path), 0o755); err != nil {
			return err
		}
		perm := os.FileMode(0o644)
		if a.Executable {
			perm = 0o755
		}
		if err := os.WriteFile(a.Path, []byte(a.Content), perm); err != nil {
			return err
		}
		// WriteFile honours umask, which can mask the exec bit even when
		// perm sets it. Re-chmod so the bit survives on tight-umask shells.
		if a.Executable {
			return os.Chmod(a.Path, perm)
		}
		return nil
	case target.ModeBlock:
		return block.Inject(a.Path, block.CurrentMarker, a.Content)
	default:
		return fmt.Errorf("unknown write mode %q", a.Mode)
	}
}
