package render

import (
	"strings"
	"testing"

	"github.com/matryer/is"
)

func TestBanner_NamesSource(t *testing.T) {
	is := is.New(t)
	b := Banner(".hatch/_skills/review-pr/SKILL.md")
	is.True(strings.HasPrefix(b, "<!--"))                             // HTML comment
	is.True(strings.HasSuffix(b, "-->"))                              // closed
	is.True(strings.Contains(b, ".hatch/_skills/review-pr/SKILL.md")) // names the source
	is.True(strings.Contains(b, "hatch gen"))                         // tells you how to regenerate
}

func TestBanner_GenericWhenNoSource(t *testing.T) {
	is := is.New(t)
	b := Banner("")
	is.True(strings.Contains(b, "Generated by hatch")) // still identifies origin
	is.True(!strings.Contains(b, "from "))             // no dangling "from <empty>"
}

func TestPrependBanner(t *testing.T) {
	is := is.New(t)
	is.Equal(PrependBanner("body", ""), "body")           // no banner → unchanged
	is.Equal(PrependBanner("", "BAN"), "BAN")             // empty body → just the banner
	is.Equal(PrependBanner("body", "BAN"), "BAN\n\nbody") // both → banner, blank line, body
}
