package render

// Banner returns a one-line HTML-comment banner marking a file as
// hatch-generated and pointing at the authoring source, so a human who opens
// a file-owned output (a SKILL.md, a .mdc rule, a command file) sees at a
// glance that edits there are overwritten by `hatch gen`.
//
// sourcePath is the `.hatch/...` source file; when empty (e.g. the
// auto-injected meta skill, which has no on-disk source) a generic banner is
// returned. HTML comments render harmlessly in every markdown-family format
// hatch writes file-owned output for.
func Banner(sourcePath string) string {
	if sourcePath == "" {
		return "<!-- Generated by hatch. Do not edit directly; edit the .hatch/ source and run `hatch gen`. -->"
	}
	return "<!-- Generated by hatch from " + sourcePath + ". Do not edit directly; edit that file and run `hatch gen`. -->"
}

// PrependBanner places banner above body, separated by a blank line. An empty
// banner returns body unchanged; an empty body returns just the banner (so the
// banner is still emitted for a source whose body is empty).
func PrependBanner(body, banner string) string {
	if banner == "" {
		return body
	}
	if body == "" {
		return banner
	}
	return banner + "\n\n" + body
}
